sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- cd rpi-alpine && docker build -t raigen/fhem:rpi-alpine .
- cd ../rpi-alpine_speedtest && docker build -t raigen/fhem:rpi-alpine_speedtest .
# test image
#- docker run hypriot/rpi-mysql mysql --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push raigen/fhem:rpi-alpine
    docker push raigen/fhem:rpi-alpine_speedtest
  fi
